<?php

namespace APIRestLicorneBundle\Repository;

/**
 * EcurieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EcurieRepository extends \Doctrine\ORM\EntityRepository
{
}
