<?php

namespace APIRestLicorneBundle\Repository;

/**
 * FideliteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FideliteRepository extends \Doctrine\ORM\EntityRepository
{
}
