<?php

namespace APIRestLicorneBundle\Repository;
use APIRestLicorneBundle\Entity\Ecurie;
use APIRestLicorneBundle\Entity\Produit;

/**
 * PrixRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrixRepository extends \Doctrine\ORM\EntityRepository
{
    public function findPrixProduit(Ecurie $ecurie, Produit $produit){
        $qb = $this->createQueryBuilder('p');

        $qb
            ->where('p.produit = :produit')
            ->setParameter('produit', $produit->getId())
            ->andWhere('p.ecurie = :ecurie')
            ->setParameter('ecurie', $ecurie->getId())
        ;

        return $qb
            ->getQuery()
            ->getOneOrNullResult()
            ;
    }

    public function findLastProduit(){
        return $this
            ->createQueryBuilder('p')
            ->orderBy('p.id', 'DESC')
            ->getQuery()
            ->setMaxResults(3)
            ->getResult()
            ;
    }

}
