api_rest_licorne:
    resource: "@APIRestLicorneBundle/Controller/"
    type:     annotation
    prefix:   /api

client:
    type: rest
    resource: APIRestLicorneBundle\Controller\ClientController
    prefix: /api

adresse:
    type: rest
    resource: APIRestLicorneBundle\Controller\AdresseController
    prefix: /api