api_rest_licorne:
    resource: "@APIRestLicorneBundle/Controller/"
    type:     annotation
    prefix:   /api

client:
    type: rest
    resource: APIRestLicorneBundle\Controller\ClientController
    prefix: /api

adresse:
    type: rest
    resource: APIRestLicorneBundle\Controller\AdresseController
    prefix: /api

produit:
    type: rest
    resource: APIRestLicorneBundle\Controller\ProduitController
    prefix: /api

pays:
    type: rest
    resource: APIRestLicorneBundle\Controller\PaysController
    prefix: /api

vente:
    type: rest
    resource: APIRestLicorneBundle\Controller\VenteController
    prefix: /api

typestock:
    type: rest
    resource: APIRestLicorneBundle\Controller\TypeStockController
    prefix: /api

categorie:
    type: rest
    resource: APIRestLicorneBundle\Controller\CategorieController
    prefix: /api

file:
    type: rest
    resource: APIRestLicorneBundle\Controller\FileController
    prefix: /api

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc