var testNS = testNS || {};

(function () {

    testNS.entityManagerFactory = function () {
        var metadataStore = new breeze.MetadataStore();
        metadataStore.importMetadata(testNS.breezeMetaData);
        var breezeEntityManager = new breeze.EntityManager({
            serviceName: 'breeze/breezedataservice',
            metadataStore: metadataStore
        });

        return breezeEntityManager;
    };

    //data.entityManager.metadataStore.exportMetadata() (run this in the dev console after a promise returns)
    testNS.breezeMetaData =
    {
        "metadataVersion": "1.0.5",
        "namingConvention": "camelCase",
        "localQueryComparisonOptions": "caseInsensitiveSQL",
        "dataServices": [
          {
              "serviceName": "breeze/breezedataservice/",
              "hasServerMetadata": true,
              //"jsonResultsAdapter": "webApi_default",
              "useJsonp": false
          }
        ],
        "structuralTypes": [
          {
              "shortName": "Licorne",
              "namespace": "LicorneManager.Model",
              "autoGeneratedKeyType": "Identity",
              "defaultResourceName": "Licornes",
              "dataProperties": [
                {
                    "name": "id",
                    "dataType": "Int32",
                    "isNullable": false,
                    "defaultValue": 0,
                    "isPartOfKey": true,
                    "validators": [
                      {
                          "name": "required"
                      },
                      {
                          "name": "int32"
                      }
                    ]
                },
                {
                    "name": "firstName",
                    "dataType": "String",
                    "maxLength": 50,
                    "validators": [
                      {
                          "maxLength": 50,
                          "name": "maxLength"
                      }
                    ]
                },
                {
                    "name": "lastName",
                    "dataType": "String",
                    "maxLength": 50,
                    "validators": [
                      {
                          "maxLength": 50,
                          "name": "maxLength"
                      }
                    ]
                },
                {
                    "name": "email",
                    "dataType": "String",
                    "maxLength": 100,
                    "validators": [
                      {
                          "maxLength": 100,
                          "name": "maxLength"
                      }
                    ]
                },
                {
                    "name": "address",
                    "dataType": "String",
                    "maxLength": 1000,
                    "validators": [
                      {
                          "maxLength": 1000,
                          "name": "maxLength"
                      }
                    ]
                },
                {
                    "name": "city",
                    "dataType": "String",
                    "maxLength": 50,
                    "validators": [
                      {
                          "maxLength": 50,
                          "name": "maxLength"
                      }
                    ]
                },
                {
                    "name": "stateId",
                    "dataType": "Int32",
                    "isNullable": false,
                    "defaultValue": 0,
                    "validators": [
                      {
                          "name": "required"
                      },
                      {
                          "name": "int32"
                      }
                    ]
                },
                {
                    "name": "zip",
                    "dataType": "Int32",
                    "isNullable": false,
                    "defaultValue": 0,
                    "validators": [
                      {
                          "name": "required"
                      },
                      {
                          "name": "int32"
                      }
                    ]
                },
                {
                    "name": "gender",
                    "dataType": "String",
                    "isNullable": false,
                    "defaultValue": "",
                    "validators": [
                      {
                          "name": "required"
                      },
                      {
                          "name": "string"
                      }
                    ],
                    "enumType": "Edm.Self.Gender"
                }
              ],
              "navigationProperties": [
                {
                    "name": "state",
                    "entityTypeName": "State:#LicorneManager.Model",
                    "isScalar": true,
                    "associationName": "Licorne_State",
                    "foreignKeyNames": [
                      "stateId"
                    ]
                },
                {
                    "name": "orders",
                    "entityTypeName": "Order:#LicorneManager.Model",
                    "isScalar": false,
                    "associationName": "Order_Licorne",
                    "invForeignKeyNames": [
                      "id"
                    ]
                }
              ]
          },
          {
              "shortName": "State",
              "namespace": "LicorneManager.Model",
              "autoGeneratedKeyType": "Identity",
              "defaultResourceName": "States",
              "dataProperties": [
                {
                    "name": "id",
                    "dataType": "Int32",
                    "isNullable": false,
                    "defaultValue": 0,
                    "isPartOfKey": true,
                    "validators": [
                      {
                          "name": "required"
                      },
                      {
                          "name": "int32"
                      }
                    ]
                },
                {
                    "name": "abbreviation",
                    "dataType": "String",
                    "maxLength": 2,
                    "validators": [
                      {
                          "maxLength": 2,
                          "name": "maxLength"
                      }
                    ]
                },
                {
                    "name": "name",
                    "dataType": "String",
                    "maxLength": 25,
                    "validators": [
                      {
                          "maxLength": 25,
                          "name": "maxLength"
                      }
                    ]
                }
              ]
          },
          {
              "shortName": "Order",
              "namespace": "LicorneManager.Model",
              "autoGeneratedKeyType": "Identity",
              "defaultResourceName": "Orders",
              "dataProperties": [
                {
                    "name": "id",
                    "dataType": "Int32",
                    "isNullable": false,
                    "defaultValue": 0,
                    "isPartOfKey": true,
                    "validators": [
                      {
                          "name": "required"
                      },
                      {
                          "name": "int32"
                      }
                    ]
                },
                {
                    "name": "product",
                    "dataType": "String",
                    "maxLength": 50,
                    "validators": [
                      {
                          "maxLength": 50,
                          "name": "maxLength"
                      }
                    ]
                },
                {
                    "name": "price",
                    "dataType": "Decimal",
                    "isNullable": false,
                    "defaultValue": 0,
                    "validators": [
                      {
                          "name": "required"
                      },
                      {
                          "name": "number"
                      }
                    ]
                },
                {
                    "name": "quantity",
                    "dataType": "Int32",
                    "isNullable": false,
                    "defaultValue": 0,
                    "validators": [
                      {
                          "name": "required"
                      },
                      {
                          "name": "int32"
                      }
                    ]
                },
                {
                    "name": "date",
                    "dataType": "DateTime",
                    "isNullable": false,
                    "defaultValue": "1900-01-01T07:00:00.000Z",
                    "validators": [
                      {
                          "name": "required"
                      },
                      {
                          "name": "date"
                      }
                    ]
                },
                {
                    "name": "licorneId",
                    "dataType": "Int32",
                    "isNullable": false,
                    "defaultValue": 0,
                    "validators": [
                      {
                          "name": "required"
                      },
                      {
                          "name": "int32"
                      }
                    ]
                }
              ],
              "navigationProperties": [
                {
                    "name": "licorne",
                    "entityTypeName": "Licorne:#LicorneManager.Model",
                    "isScalar": true,
                    "associationName": "Order_Licorne",
                    "foreignKeyNames": [
                      "licorneId"
                    ]
                }
              ]
          }
        ],
        "resourceEntityTypeMap": {
            "Licornes": "Licorne:#LicorneManager.Model",
            "States": "State:#LicorneManager.Model",
            "Orders": "Order:#LicorneManager.Model"
        }
    }
}());
