<?php

namespace APIRestLicorneBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;



/**
 * AlertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProdutRepository extends EntityRepository
{
    /**
     *
     *  Récupère la liste des produits avec les prix dans l'écurie de Lille
     * @return array
     */
    public function findWithPrixAndLille(){

        $qb=$this->createQueryBuilder('p');

        $query = $this->createQueryBuilder('p')
            ->join('p.', 'u')
            ->andWhere($qb->expr()->isNull('a.deleteDate'))
            ->andWhere('a.city = :city')
            ->setParameter('city',$advert->getCity()->getId())
            ->andWhere('a.rentalMin  <= :rental')
            ->setParameter('rental',$advert->getRental())
            ->andWhere('a.rentalMax  >= :rental')
            ->setParameter('rental',$advert->getRental());

        if($advert instanceof Rent){
            $query
                ->andWhere('a.surfaceMin  <= :surface')
                ->setParameter('surface',$advert->getSurface())
                ->andWhere('a.surfaceMax  >= :surface')
                ->setParameter('surface',$advert->getSurface())
                ->andWhere('a.categorie = :categorie')
                ->setParameter('categorie','rent');
        }
        else{
            $query
                ->andWhere('a.surfaceMin  <= :surface')
                ->setParameter('surface',$advert->getSurfaceRoom())
                ->andWhere('a.surfaceMax  >= :surface')
                ->setParameter('surface',$advert->getSurfaceRoom())
                ->andWhere('a.categorie = :categorie')
                ->setParameter('categorie','flatShare');
        }

        return $query->getQuery()
            ->getResult();
    }
}
